return {
	-- "akinsho/bufferline.nvim",
	-- event = "BufEnter",
	-- opts = {
	-- 	options = {
	-- 		numbers = "none",
	-- 		mode = "buffers", -- set to "tabs" to only show tabpages instead
	-- 		close_command = "bdelete! %d", -- can be a string | function, see "Mouse actions"
	-- 		right_mouse_command = "bdelete! %d", -- can be a string | function, see "Mouse actions"
	-- 		left_mouse_command = "buffer %d", -- can be a string | function, see "Mouse actions"
	-- 		middle_mouse_command = nil, -- can be a string | function, see "Mouse actions"
	-- 		indicator = {
	-- 			icon = "▎", -- this should be omitted if indicator style is not 'icon'
	-- 			style = "icon",
	-- 		},
	-- 		buffer_close_icon = "",
	-- 		modified_icon = "●",
	-- 		close_icon = "",
	-- 		left_trunc_marker = "",
	-- 		right_trunc_marker = "",
	-- 		name_formatter = function(buf) -- buf contains:
	-- 			return buf.name
	-- 		end,
	-- 		max_name_length = 35,
	-- 		max_prefix_length = 15, -- prefix used when a buffer is de-duplicated
	-- 		truncate_names = true, -- whether or not tab names should be truncated
	-- 		tab_size = 18,
	-- 		diagnostics = "nvim_lsp",
	-- 		diagnostics_update_in_insert = false,
	-- 		diagnostics_indicator = function(count)
	-- 			return "(" .. count .. ")"
	-- 		end,
	-- 		offsets = {
	-- 			{
	-- 				filetype = "fugitive",
	-- 				text = "Fugitive",
	-- 				padding = 1,
	-- 			},
	-- 			{
	-- 				filetype = "NvimTree",
	-- 				text = "File explorer",
	-- 				highlight = "Directory",
	-- 				text_align = "center",
	-- 			},
	-- 		},
	-- 		color_icons = true, -- whether or not to add the filetype icon highlights
	-- 		show_buffer_icons = true, -- disable filetype icons for buffers
	-- 		show_buffer_close_icons = true,
	-- 		show_close_icon = true,
	-- 		show_tab_indicators = true,
	-- 		show_duplicate_prefix = true, -- whether to show duplicate buffer prefix
	-- 		persist_buffer_sort = true, -- whether or not custom sorted buffers should persist
	-- 		separator_style = "thin",
	-- 		enforce_regular_tabs = false,
	-- 		always_show_bufferline = true,
	-- 		hover = {
	-- 			enabled = true,
	-- 			delay = 200,
	-- 			reveal = { "close" },
	-- 		},
	-- 	},
	-- },
	-- keys = {
	-- 	{ "<leader>Br", "<Cmd>BufferLineCloseRight<CR>", desc = "Delete buffers to the right" },
	-- 	{ "<leader>Bl", "<Cmd>BufferLineCloseLeft<CR>", desc = "Delete buffers to the left" },
	-- 	{ "<leader>Bo", "<Cmd>BufferLineCloseLeft<CR><Cmd>BufferLineCloseRight<CR>", desc = "Delete other buffers" },
	-- },
}
