return {
	"hedyhli/outline.nvim",
	event = "LspAttach",
	opts = {
		outline_window = {
			position = "right",
			auto_jump = false,
			show_relative_numbers = true,
		},
		symbols = {
			icons = {
				Namespace = { icon = "n", hl = "Include" },
				Class = { icon = "c", hl = "Type" },
				Method = { icon = "f", hl = "Function" },
				Enum = { icon = "e", hl = "Type" },
				Function = { icon = "f", hl = "Function" },
				Number = { icon = "#", hl = "Number" },
				Boolean = { icon = "⊨", hl = "Boolean" },
				Array = { icon = "󰅪", hl = "Constant" },
				Object = { icon = "⦿", hl = "Type" },
				Key = { icon = "🔐", hl = "Type" },
				Null = { icon = "NULL", hl = "Type" },
				EnumMember = { icon = "", hl = "Identifier" },
				Struct = { icon = "𝓢", hl = "Structure" },
				Event = { icon = "🗲", hl = "Type" },
				Operator = { icon = "+", hl = "Identifier" },
				TypeParameter = { icon = "𝙏", hl = "Identifier" },
				Component = { icon = "󰅴", hl = "Function" },
				Fragment = { icon = "󰅴", hl = "Constant" },
				TypeAlias = { icon = " ", hl = "Type" },
				Parameter = { icon = " ", hl = "Identifier" },
				StaticMethod = { icon = " ", hl = "Function" },
				Macro = { icon = " ", hl = "Function" },
			},
		},
	},
	keys = {
		{ "<leader>o", "<cmd>Outline!<cr>", desc = "Toggle Outline" },
	},
}
